#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: adminuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILKJ7ZfIW0TfZW7i58V0LkcNmtC4PQC2zEv+5A6T7yWm klimov.lamer@gmail.com
